### ISSUE TITLE
Handle media selectors (AtRule)

### ISSUE THREAD

**Issue by ol0lll** [BurdaMagazinOrg/css-sniper#5]
* When removing a selector it is also removed inside @-rules.
* Removal of @-rules  does not work.
```
node_modules/css-tree/lib/tokenizer/Tokenizer.js:586
        throw new CssSyntaxError(
        ^
CssSyntaxError: Selector is expected
    at Tokenizer.error (node_modules/css-tree/lib/tokenizer/Tokenizer.js:586:15)
    at Object.parse [as Selector] (node_modules/css-tree/lib/syntax/node/Selector.js:20:26)
    at Object.parse [as SelectorList] (node_modules/css-tree/lib/syntax/node/SelectorList.js:18:38)
    at Object.<anonymous> (node_modules/css-tree/lib/parser/create.js:9:26)
    at Object.parse (node_modules/css-tree/lib/parser/create.js:153:39)
    at getSelectorAndDeclarations (node_modules/css-sniper/importer.js:67:40)
    at Array.map (<anonymous>)
    at parseImportString (node_modules/css-sniper/importer.js:54:58)
Segmentation fault: 11
```

**Comment by ol0lll** [comment]
fixed with #6
